### ISSUE TITLE
No longer working with Unraid 6.9.2

### ISSUE THREAD

**Issue by mervin39** [dmacias72/unRAID-libvirtwol#3]
Installed plugin on Unraid via Community Apps but VM manager doesn't show the expected options are missing from the VM Manager page on the Unraid webui. I have recently discovered this plugin so have never seen it working, but I understand it should be configured from the VM Manager.

This thread on the Unraid forums seem to indicate that others are having the same problem

https://forums.unraid.net/topic/42320-wake-on-lan-for-virtual-machines-for-61/page/5/

**Comment by yanghe005** [comment]
我也遇到这个问题了，希望大佬尽快更新一版可以在6.9.2中使用的插件。

**Comment by mervin39** [comment]
The following workaround fixes it for me on Unraid:
1. Uninstall Python2 from the Nerd Pack Plugin
2. cli into your unraid
3. Download Python2 for Slackware: wget https://slackware.uk/slackware/slackware64-14.2/slackware64/d/python-2.7.11-x86_64-2.txz
4. Install Python2: upgradepkg --install-new python-2.7.11-x86_64-2.txz

via https://forums.unraid.net/topic/42320-wake-on-lan-for-virtual-machines-for-61/?do=findComment&comment=1029485

**Comment by yanghe005** [comment]
> The following workaround fixes it for me on Unraid:
> 
> 1. Uninstall Python2 from the Nerd Pack Plugin
> 2. cli into your unraid
> 3. Download Python2 for Slackware: wget https://slackware.uk/slackware/slackware64-14.2/slackware64/d/python-2.7.11-x86_64-2.txz
> 4. Install Python2: upgradepkg --install-new python-2.7.11-x86_64-2.txz
> 
> via https://forums.unraid.net/topic/42320-wake-on-lan-for-virtual-machines-for-61/?do=findComment&comment=1029485

可以了  感谢

**Comment by dmacias72** [comment]
I reverted the Nerdpack python 2

**Comment by cksonny** [comment]
> The following workaround fixes it for me on Unraid:
> 
> 1. Uninstall Python2 from the Nerd Pack Plugin
> 2. cli into your unraid
> 3. Download Python2 for Slackware: wget https://slackware.uk/slackware/slackware64-14.2/slackware64/d/python-2.7.11-x86_64-2.txz
> 4. Install Python2: upgradepkg --install-new python-2.7.11-x86_64-2.txz
> 
> via https://forums.unraid.net/topic/42320-wake-on-lan-for-virtual-machines-for-61/?do=findComment&comment=1029485

Works for me! Thank you.
